### ISSUE TITLE
`devel` deprecation warning for Inertia

### ISSUE THREAD

**Issue by rwblickhan** [ubclaunchpad/homebrew-tap#15]
Just got this deprecation warning when installing something completely unrelated (I think Homebrew went ahead and bumped Inertia as well):
```
Warning: Calling 'devel' blocks in formulae is deprecated! Use 'head' blocks or @-versioned formulae instead.
Please report this issue to the ubclaunchpad/tap tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/ubclaunchpad/homebrew-tap/inertia.rb:12
```

**Comment by iKevinY** [comment]
Sigh, not sure why they made this deprecation warning global as opposed to just when you attempt to update the specific formula. I'll remove the development block.

**Comment by bobheadxi** [comment]
Thanks @iKevinY !
