### ISSUE TITLE
Grant write permissions to @ubclaunchpad/all

### ISSUE THREAD

**Issue by bobheadxi** [ubclaunchpad/homebrew-tap#3]
@iKevinY Might be a good idea to grant write permissions to everyone in Launch Pad and restrict permissions using `master` protection and `CODEOWNERS`, otherwise we have to fork to submit a PR 😅 

```bash
bobbook:homebrew-tap robertlin$ git push origin HEAD
remote: Permission to ubclaunchpad/homebrew-tap.git denied to bobheadxi.
fatal: unable to access 'https://github.com/ubclaunchpad/homebrew-tap.git/': The requested URL returned error: 403
```

**Comment by iKevinY** [comment]
Whoops, forgot about that! Should be addressed now! 😅
